add_newline = false
command_timeout = 200
format = "$os$username$directory$git_branch$git_status$character"
right_format = "$cmd_duration"
[os]

format = "[$symbol]($style) "
style = "bold white"
disabled = false

[os.symbols]
Linux = " "
Arch = " "
Ubuntu = " "
Macos = " "
Windows = " "

[character]
error_symbol = "[✗](bold red)"
success_symbol = "[❯](bold green)"

[username]
format = "[$user]($style) "
style_user = "bold yellow"
style_root = "bold red"
show_always = true

[directory]
truncation_length = 6
truncation_symbol = "…/"
style = "bold cyan"
format = "[$path]($style)[$read_only]($read_only_style) "
home_symbol = "~"
truncate_to_repo = false

[git_branch]
format = "[$symbol$branch]($style) "
style = "bold purple"
symbol = " "

[git_status]
format     = '[$all_status]($style)'
style      = "cyan"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
modified   = "[](bold yellow) "
staged     = "[●](bold green) "
conflicted = "[✖](bold red) "
untracked  = "[?](bold white) "
up_to_date = "[ ](bold green) "
renamed    = ""
deleted    = "[!](bold red)"

[cmd_duration]
min_time = 0
format = "⏱  [$duration]($style)"
style = "bold purple"
